spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/mithoconfectionary
    username: postgres
    password: suyashstha
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
